"""
Codegen — writes the Patrol/integration_test Dart file that drives the app
on the device, makes HTTP calls back to the Mac for AI/HITL decisions, and
takes screenshots after each step.

Designed to work with ANY Flutter app: doesn't hardcode screen-specific
nav. Drives the app via the action JSON returned by the host's /nav
endpoint, looping until the host says 'done'.
"""
import re
from pathlib import Path
from typing import Optional


HARNESS_PATH = "integration_test/_flowtest_v2_test.dart"


def _read_pubspec_name(project_root: Path) -> str:
    pubspec = project_root / "pubspec.yaml"
    for line in pubspec.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("name:"):
            return line.split(":", 1)[1].strip().strip("'\"")
    raise RuntimeError(f"No name in {pubspec}")


def _detect_app_root(main_dart_path: Path) -> str:
    src = main_dart_path.read_text(encoding="utf-8")
    m = (re.search(r"runApp\s*\(\s*const\s+(\w+)\s*\(\s*\)\s*\)", src)
         or re.search(r"runApp\s*\(\s*(\w+)\s*\(\s*\)\s*\)", src))
    return m.group(1) if m else "MyApp"


def _ensure_pubspec(project_root: Path) -> bool:
    pubspec = project_root / "pubspec.yaml"
    text = pubspec.read_text(encoding="utf-8")
    needs = []
    if "integration_test:" not in text:
        needs.append("  integration_test:\n    sdk: flutter\n")
    if "http: " not in text and "  http:" not in text:
        needs.append("  http: ^1.2.0\n")
    if not needs:
        return False
    if "dev_dependencies:" not in text:
        return False
    block = "dev_dependencies:\n" + "".join(needs)
    text = text.replace("dev_dependencies:\n", block, 1)
    pubspec.write_text(text, encoding="utf-8")
    return True


def _render_dart(package_name: str, app_root: str, port: int,
                 target_screens: list[str]) -> str:
    targets_dart = ",\n  ".join(f"'{s}'" for s in target_screens)
    return f"""// AUTO-GENERATED by FlowTest AI Phase 4 v2. Do not edit by hand.
// Drives the real app on a connected device, talks to the Mac host over
// HTTP for every navigation/verification decision, and screenshots each
// reached screen.
import 'dart:async';
import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:http/http.dart' as http;

import 'package:{package_name}/main.dart';

const _hostBase = 'http://127.0.0.1:{port}';
const _maxStepsPerTarget = 12;

const List<String> _targetScreens = [
  {targets_dart}
];

Future<Map<String, dynamic>> _post(String path, Map<String, dynamic> body) async {{
  // On any host failure (quota, network, server error) we degrade gracefully
  // instead of crashing the whole test. Returning a skip-shaped fallback lets
  // the loop move on to the next target screen.
  try {{
    final res = await http.post(
      Uri.parse('$_hostBase$path'),
      headers: const {{'Content-Type': 'application/json'}},
      body: jsonEncode(body),
    ).timeout(const Duration(seconds: 90));
    if (res.statusCode >= 400) {{
      print('FLOWTEST_HOST_ERROR:$path:${{res.statusCode}}:${{res.body}}');
      return {{'action': 'skip', 'matches_expected': false, 'host_error': res.statusCode}};
    }}
    return jsonDecode(res.body) as Map<String, dynamic>;
  }} catch (e) {{
    print('FLOWTEST_HOST_EXCEPTION:$path:$e');
    return {{'action': 'skip', 'matches_expected': false, 'host_exception': '$e'}};
  }}
}}

Future<Uint8List> _shot(IntegrationTestWidgetsFlutterBinding binding,
    WidgetTester tester) async {{
  await tester.pump();
  return await binding.takeScreenshot('flowtest_step') as Uint8List;
}}

Future<void> _settle(WidgetTester tester, {{int seconds = 8}}) async {{
  try {{
    await tester.pumpAndSettle(
      const Duration(milliseconds: 100),
      EnginePhase.sendSemanticsUpdate,
      Duration(seconds: seconds),
    );
  }} catch (_) {{
    await tester.pump(const Duration(milliseconds: 500));
  }}
}}

Future<void> _executeAction(
    WidgetTester tester, Map<String, dynamic> action) async {{
  final kind = action['action'] as String? ?? 'skip';
  final selector = action['selector'] as String? ?? '';
  final input = action['input_text'] as String?;
  final waitAfter = (action['wait_after_seconds'] as num?)?.toInt() ?? 3;

  switch (kind) {{
    case 'tap_text':
      final f = find.text(selector);
      if (f.evaluate().isNotEmpty) await tester.tap(f.first);
      break;
    case 'tap_icon':
      final iconCode = _iconFromName(selector);
      if (iconCode != null) {{
        final f = find.byIcon(iconCode);
        if (f.evaluate().isNotEmpty) await tester.tap(f.first);
      }}
      break;
    case 'tap_widget_type':
    case 'tap_first_of_type':
      final all = find.byElementPredicate((e) => e.widget.runtimeType.toString() == selector);
      if (all.evaluate().isNotEmpty) await tester.tap(all.first);
      break;
    case 'enter_text':
      final fieldIdx = (action['field_index'] as num?)?.toInt() ?? 0;
      final fields = find.byType(TextField);
      final list = fields.evaluate().toList();
      if (list.isNotEmpty && input != null) {{
        final clamped = fieldIdx.clamp(0, list.length - 1);
        await tester.enterText(fields.at(clamped), input);
        await tester.pump();
      }}
      break;
    case 'scroll_down':
      await tester.drag(find.byType(Scaffold).first, const Offset(0, -300));
      break;
    case 'scroll_up':
      await tester.drag(find.byType(Scaffold).first, const Offset(0, 300));
      break;
    case 'back':
      try {{
        Navigator.of(tester.element(find.byType(Scaffold).first)).pop();
      }} catch (_) {{}}
      break;
    case 'wait':
      // pumpAndSettle already covered by _settle below.
      break;
    case 'skip':
    case 'hitl':
    default:
      break;
  }}
  await _settle(tester, seconds: waitAfter);
}}

IconData? _iconFromName(String name) {{
  // Not exhaustive — common Material icons mapped by the names AI is likely
  // to return. Falls back to null which makes the tap a no-op.
  const map = {{
    'bookmark': Icons.bookmark,
    'bookmark_border': Icons.bookmark_border,
    'add': Icons.add,
    'delete': Icons.delete,
    'edit': Icons.edit,
    'search': Icons.search,
    'menu': Icons.menu,
    'close': Icons.close,
    'arrow_back': Icons.arrow_back,
    'home': Icons.home,
    'settings': Icons.settings,
    'person': Icons.person,
    'shopping_cart': Icons.shopping_cart,
    'favorite': Icons.favorite,
    'favorite_border': Icons.favorite_border,
    'check': Icons.check,
    'visibility': Icons.visibility,
    'notifications': Icons.notifications,
  }};
  return map[name.replaceFirst('Icons.', '').replaceAll('-', '_')];
}}

Future<void> _navigateTo(IntegrationTestWidgetsFlutterBinding binding,
    WidgetTester tester, String target) async {{
  for (var step = 0; step < _maxStepsPerTarget; step++) {{
    final shot = await _shot(binding, tester);
    final action = await _post('/nav', {{
      'screenshot_b64': base64Encode(shot),
      'current_screen_guess': step == 0 ? 'unknown' : 'in_progress',
      'target_screen': target,
    }});
    final actionKind = action['action'] as String? ?? 'skip';
    if (actionKind == 'skip') {{
      // Save whatever the screen looks like even though we gave up — partial
      // progress is still useful for visual review.
      await _post('/screenshot', {{
        'name': '${{_safe(target)}}_partial_step$step',
        'screenshot_b64': base64Encode(shot),
      }});
      return;
    }}
    await _executeAction(tester, action);

    // Verify after each step. Once verifier says we're on target, stop.
    final verifyShot = await _shot(binding, tester);
    final verify = await _post('/verify', {{
      'screenshot_b64': base64Encode(verifyShot),
      'expected_screen': target,
    }});
    if (verify['matches_expected'] == true) {{
      // Save final screenshot for vision analysis.
      await _post('/screenshot', {{
        'name': '${{_safe(target)}}_native',
        'screenshot_b64': base64Encode(verifyShot),
      }});
      return;
    }}
    // Save intermediate screenshot so a partial run still has artifacts.
    if (step % 3 == 0) {{
      await _post('/screenshot', {{
        'name': '${{_safe(target)}}_intermediate_step$step',
        'screenshot_b64': base64Encode(verifyShot),
      }});
    }}
  }}
  // Out of steps — save final state for inspection.
  final finalShot = await _shot(binding, tester);
  await _post('/screenshot', {{
    'name': '${{_safe(target)}}_gaveup',
    'screenshot_b64': base64Encode(finalShot),
  }});
  print('FLOWTEST_NOTE: gave up reaching target $target after $_maxStepsPerTarget steps.');
}}

String _safe(String s) => s.toLowerCase().replaceAll(RegExp(r'[^a-z0-9]+'), '_');

Future<void> _resetToHome(WidgetTester tester) async {{
  // Pop the navigator stack until we cannot pop further. Keeps each target
  // run independent so flaky state from one screen doesn't bleed into next.
  for (var i = 0; i < 8; i++) {{
    try {{
      final nav = Navigator.of(tester.element(find.byType(Scaffold).first));
      if (!nav.canPop()) break;
      nav.pop();
      await _settle(tester);
    }} catch (_) {{
      break;
    }}
  }}
}}

void main() {{
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  // Catch every Flutter framework error so a single buggy screen in the
  // app under test doesn't terminate exploration of the remaining screens.
  FlutterError.onError = (FlutterErrorDetails details) async {{
    final summary = details.exceptionAsString();
    print('FLOWTEST_FLUTTER_ERROR: $summary');
    try {{
      await _post('/flutter_error', {{
        'error': summary,
        'stack': details.stack?.toString() ?? '',
        'context': details.context?.toString() ?? '',
      }});
    }} catch (_) {{}}
  }};

  testWidgets('FlowTest v2 — drive real device with AI nav',
      (WidgetTester tester) async {{
    await tester.pumpWidget(const SizedBox.shrink());
    await binding.convertFlutterSurfaceToImage();
    await tester.pump();

    await tester.pumpWidget(const {app_root}());
    await _settle(tester, seconds: 10);

    // Capture and store HOME first.
    final homeShot = await _shot(binding, tester);
    await _post('/screenshot', {{
      'name': 'home_native',
      'screenshot_b64': base64Encode(homeShot),
    }});

    // Don't reset to home between targets — auth state and any setup work
    // (login, permissions) carries forward. AI navigates from current state
    // to next target naturally. Wrap each target in try/catch so app
    // crashes during one target don't prevent the next from running.
    for (final target in _targetScreens) {{
      try {{
        await _navigateTo(binding, tester, target);
      }} catch (e, st) {{
        print('FLOWTEST_TARGET_FAILED: $target: $e');
        try {{
          await _post('/flutter_error', {{
            'error': '$e',
            'stack': '$st',
            'context': 'while navigating to $target',
          }});
        }} catch (_) {{}}
        // Try to recover the navigator stack so the next target can start
        // from a sensible place.
        try {{
          for (var i = 0; i < 4; i++) {{
            final nav = Navigator.of(tester.element(find.byType(Scaffold).first));
            if (!nav.canPop()) break;
            nav.pop();
            await _settle(tester, seconds: 2);
          }}
        }} catch (_) {{}}
      }}
    }}

    await _post('/done', {{'summary': 'ok'}});
  }}, timeout: const Timeout(Duration(minutes: 20)));
}}
"""


def generate_harness(
    project_root: str | Path,
    app_map: dict,
    *,
    port: int = 5000,
) -> dict:
    project_root = Path(project_root).resolve()
    package_name = _read_pubspec_name(project_root)
    pubspec_modified = _ensure_pubspec(project_root)

    main_dart = project_root / "lib" / "main.dart"
    if not main_dart.is_file():
        raise FileNotFoundError(f"No lib/main.dart in {project_root}")
    app_root = _detect_app_root(main_dart)

    # Build target screen list from app_map; entry screen captured pre-loop,
    # so target list is "everything else".
    screens = app_map.get("screens", [])
    if not screens:
        raise RuntimeError("App map has no screens.")
    target_names = [s["name"] for s in screens[1:]]

    dart = _render_dart(package_name, app_root, port, target_names)
    out = project_root / HARNESS_PATH
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(dart, encoding="utf-8")

    return {
        "harness_path": str(out),
        "package": package_name,
        "app_root": app_root,
        "target_screens": target_names,
        "port": port,
        "pubspec_modified": pubspec_modified,
    }
