"""
Phase 4 — integration_test codegen for real-device runs.

Reads the Phase 2 app map plus each screen's Dart source, generates an
integration_test file that drives the real app on a connected device:
- Pumps the actual app entry point (no MediaQuery override at native res).
- Navigates each screen using simple tap-by-text / tap-by-icon heuristics
  (one screen at a time, popping back to home after each).
- Waits for real APIs to load via real-time pumpAndSettle.
- Takes screenshots via IntegrationTestWidgetsFlutterBinding.takeScreenshot.
- Streams PNG bytes back to host as base64 over stdout (chunked) — survives
  ColorOS scoped storage, app-uninstall, and adb pull restrictions.

Multi-resolution via MediaQuery override is intentionally OMITTED here:
it works inconsistently when the simulated size exceeds the real device's
logical screen (MaterialApp creates its own MediaQuery from the View, not
from outer context). For multi-res coverage, run Phase 3 (widget tests)
in parallel.
"""
import json
import re
from pathlib import Path
from typing import Optional


HARNESS_PATH = "integration_test/_flowtest_real_device_test.dart"


def _read_pubspec_name(project_root: Path) -> str:
    pubspec = project_root / "pubspec.yaml"
    for line in pubspec.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line.startswith("name:"):
            return line.split(":", 1)[1].strip().strip("'\"")
    raise RuntimeError(f"Could not find package name in {pubspec}")


def _ensure_pubspec_deps(project_root: Path) -> bool:
    """Add integration_test sdk dep if missing. Return True if file modified."""
    pubspec = project_root / "pubspec.yaml"
    text = pubspec.read_text(encoding="utf-8")
    if "integration_test:" in text:
        return False
    if "dev_dependencies:" not in text:
        return False  # weird project layout, bail
    new_block = (
        "dev_dependencies:\n"
        "  integration_test:\n"
        "    sdk: flutter\n"
    )
    text = text.replace("dev_dependencies:\n", new_block, 1)
    pubspec.write_text(text, encoding="utf-8")
    return True


def _detect_app_root(main_dart_path: Path) -> str:
    """Pull the runApp() argument so we know which widget is the app root."""
    src = main_dart_path.read_text(encoding="utf-8")
    m = re.search(r"runApp\s*\(\s*const\s+(\w+)\s*\(\s*\)\s*\)", src)
    if m:
        return m.group(1)
    m = re.search(r"runApp\s*\(\s*(\w+)\s*\(\s*\)\s*\)", src)
    if m:
        return m.group(1)
    return "MyApp"


def _slug(rel: str) -> str:
    return re.sub(r"[^a-zA-Z0-9]+", "_", Path(rel).stem).lower()


def _render_dart(package_name: str, app_root: str, screens: list[dict]) -> str:
    """Build the integration_test Dart file."""
    # Each screen entry: {name, file, slug, nav: [tap-by-text/icon steps]}.
    # For now we use simple heuristics derived from app_map nav triggers; this
    # is hardcoded here because mapping arbitrary triggers to find.* calls
    # generally needs AI assistance (Phase 5+).
    blocks = []
    home_slug = screens[0]["slug"] if screens else "home"
    for sc in screens:
        nav_lines = "\n      ".join(sc.get("nav", []))
        blocks.append(f"""
      // ---- {sc['name']} ----
      print('FLOWTEST_NAV_BEGIN:{sc['slug']}');
      {nav_lines}
      await _settle(tester);
      await _shoot(binding, tester, '{sc['slug']}_native');
      // Pop back to home for the next screen.
      try {{
        while (Navigator.of(tester.element(find.byType(Scaffold).first)).canPop()) {{
          Navigator.of(tester.element(find.byType(Scaffold).first)).pop();
          await _settle(tester);
        }}
      }} catch (_) {{}}
      print('FLOWTEST_NAV_END:{sc['slug']}');
""")

    return f"""// AUTO-GENERATED by FlowTest AI Phase 4. Do not edit by hand.
// Re-running step4_real_device.py overwrites this file.
import 'dart:async';
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';

import 'package:{package_name}/main.dart';

Future<void> _emit(String name, List<int> bytes) async {{
  const chunkSize = 1024;
  final b64 = base64Encode(bytes);
  print('FLOWTEST_PNG_BEGIN:$name:${{b64.length}}');
  for (var i = 0; i < b64.length; i += chunkSize) {{
    final end = (i + chunkSize < b64.length) ? i + chunkSize : b64.length;
    print('FLOWTEST_PNG_CHUNK:$name:${{b64.substring(i, end)}}');
    if (i % (chunkSize * 16) == 0) {{
      await Future<void>.delayed(const Duration(milliseconds: 5));
    }}
  }}
  print('FLOWTEST_PNG_END:$name');
}}

Future<void> _settle(WidgetTester tester, {{Duration max = const Duration(seconds: 10)}}) async {{
  try {{
    await tester.pumpAndSettle(const Duration(milliseconds: 100), EnginePhase.sendSemanticsUpdate, max);
  }} catch (_) {{
    await tester.pump(const Duration(milliseconds: 500));
  }}
}}

Future<void> _shoot(IntegrationTestWidgetsFlutterBinding binding, WidgetTester tester, String name) async {{
  await tester.pump();
  final bytes = await binding.takeScreenshot(name);
  await _emit(name, bytes);
}}

void main() {{
  final binding = IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  testWidgets('FlowTest Phase 4: capture all screens on real device',
      (WidgetTester tester) async {{
    await tester.pumpWidget(const SizedBox.shrink());
    await binding.convertFlutterSurfaceToImage();
    await tester.pump();

    // Pump the real app once. Subsequent screens use real navigation, not
    // pumpWidget swaps, so app state (route stack, services) is preserved.
    await tester.pumpWidget(const {app_root}());
    await _settle(tester, max: const Duration(seconds: 10));
    await _shoot(binding, tester, '{home_slug}_native');
{''.join(blocks)}
  }}, timeout: const Timeout(Duration(minutes: 10)));
}}
"""


def generate_harness(
    project_root: str | Path,
    app_map_path: str | Path,
    *,
    nav_overrides: Optional[dict[str, list[str]]] = None,
) -> dict:
    """Build harness file in target project.

    nav_overrides maps screen_slug -> list of Dart navigation lines that get
    the app from HOME to that screen. Defaults to a single tap-by-text on the
    screen's purpose if no override given (works for movie_browser-class apps).
    """
    project_root = Path(project_root).resolve()
    app_map = json.loads(Path(app_map_path).read_text(encoding="utf-8"))
    package_name = _read_pubspec_name(project_root)
    pubspec_modified = _ensure_pubspec_deps(project_root)

    main_dart = project_root / "lib" / "main.dart"
    if not main_dart.is_file():
        raise FileNotFoundError(f"No lib/main.dart in {project_root}")
    app_root = _detect_app_root(main_dart)

    screens = []
    for s in app_map.get("screens", []):
        slug = _slug(s["file"])
        # Skip the entry/home screen itself; we capture it before the loop.
        if slug == _slug(app_map["screens"][0]["file"]):
            continue
        # Default nav: tap by screen name (or first cross-cutting category).
        # Real-world: nav_overrides should be supplied per project for accuracy.
        default_nav = [
            f"final t_{slug} = find.text('{s['name']}');",
            f"if (t_{slug}.evaluate().isNotEmpty) {{ "
            f"await tester.tap(t_{slug}.first); }} "
            f"else {{ print('FLOWTEST_NOTE:{slug}: tile by name not found'); return; }}",
            "await _settle(tester, max: const Duration(seconds: 12));",
        ]
        nav = (nav_overrides or {}).get(slug, default_nav)
        screens.append({
            "name": s["name"],
            "slug": slug,
            "nav": nav,
        })

    # Always include the entry screen as the first one (captured pre-loop).
    entry = app_map["screens"][0]
    entry_slug = _slug(entry["file"])
    screens.insert(0, {"name": entry["name"], "slug": entry_slug, "nav": []})

    dart = _render_dart(package_name, app_root, screens)
    harness_path = project_root / HARNESS_PATH
    harness_path.parent.mkdir(parents=True, exist_ok=True)
    harness_path.write_text(dart, encoding="utf-8")

    return {
        "harness_path": str(harness_path),
        "package": package_name,
        "app_root": app_root,
        "screens": [s["slug"] for s in screens],
        "pubspec_modified": pubspec_modified,
    }
